### ISSUE TITLE
Preliminary test of integration of PySM

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#116]
I believe it would be useful to start wrapping our mind around integrating `PySM` (https://github.com/bthorne93/PySM_public) into `TOAST`.
We don't need to implement it yet, but it would be interesting to understand:

* if this integration would pose any constraint to `TOAST` or to `PySM`
* how `PySM` can leverage some `TOAST` features

In particular `PySM` is now a serial code but the core developers would like to make it parallel, first multi-threaded and then (possibly) distributed, can we do in a way that makes integration with `TOAST` easier?

@tskisner do you have already anything in mind about this? (we can discuss at the next call if it is quicker)

**Comment by zonca** [comment]
I'll start writing a code based on the `OpSim` class see:

Scanning from a map.  Top-level operator:
https://github.com/hpc4cmb/toast/blob/b985b3dde91df0fdcfdc0aa24e9cf184bbb03e97/src/python/tod/sim_det_map.py#L116
This calls a function in the compiled library to do the scanning:
https://github.com/hpc4cmb/toast/blob/b985b3dde91df0fdcfdc0aa24e9cf184bbb03e97/src/python/ctoast.py.in#L836
and then:
https://github.com/hpc4cmb/toast/blob/b985b3dde91df0fdcfdc0aa24e9cf184bbb03e97/src/libtoast/tod/toast/sim_map.hpp#L15

@keskitalo you proposed to use "global" pixels (map spread on processes with no overlap) instead of "local" pixels, are global indices already available in the code?

@tskisner what is the more suitable test case I can use for testing this?

**Comment by zonca** [comment]
@tskisner I checked out `tiny_satellite_shell.sh`, it uses `toast_satellite_sim.py`, I think a simpler script that uses directly the TOAST API would be probably easier for testing the PySM operator, would you have something like that?

**Comment by tskisner** [comment]
The global pixel indices are what is actually stored in the cache.  These are then converted into locally hit submap and pixel within the submap.  Each process stores locally the submaps which are hit by its local data:  https://github.com/hpc4cmb/toast/blob/19f6315365e97fc1472c3f80154df27db70f73d7/src/python/tod/sim_det_map.py#L174

**Comment by tskisner** [comment]
As for testing, I could create a stub of the operator and a unit test that creates fake pointing (spiral around healpix ring-ordered pixels.  I agree that the example satellite simulation pipeline is overkill for an isolated test- it is designed to show a full pipeline of operations.

**Comment by zonca** [comment]
Thanks Ted, that would ease my work a lot!

**Comment by tskisner** [comment]
See #122

**Comment by zonca** [comment]
First implementation in #137

**Comment by zonca** [comment]
followup in #152
