### ISSUE TITLE
Feedback on installing toast on Ubuntu Xenial

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#119]
here are the packages I needed to install on my Ubuntu Xenial to install TOAST:

* `pkg-config`
* `fftw3-dev` (`fftw-dev` was mentioned in the docs, but that installs FFTW2 which then is not recognized by `./configure`
* `libatlas-base-dev`

If I install `mpi4py` with `conda`, I get a `mpich` too old and I get this error:
Tried with `openmpi` and got:
‘MPI_COMM_TYPE_SHARED’ was not declared in this scope

it works fine if I install `openmpi` with `apt` and then `pip install mpi4py`

I'm still working on installing Elemental

**Comment by tskisner** [comment]
Yes, here are 2 ways I install on Ubuntu:

1.  apt-get everything, including python3-<blah> packages.  Everything just works.

2.  apt-get all compiled dependecies, including cfitsio, fftw, mpich.  Then install conda for all python packages except mpi4py.  Then install mpi4py manually using the system mpich.

Also you can look at how I build dependencies at NERSC (or elsewhere):  https://github.com/hpc4cmb/toast/tree/master/external/rules
https://github.com/hpc4cmb/toast/blob/master/external/README.md

**Comment by zonca** [comment]
ok, thanks, I got TOAST installed
