### ISSUE TITLE
More representative ground simulation example

### ISSUE THREAD

**Issue by tskisner** [hpc4cmb/toast#129]
For profiling purposes, it would be good to have a ground telescope simulation with realistic ratios of compute time for simulating noise and atmosphere, as well as pointing expansion.  @keskitalo and @jdborrill and I discussed this offline.  I believe the plan is to generate a high-resolution atmosphere slab and also use a realistic number of detectors for one (or a few) CESs.  This will use binned mapmaking since there will not be enough cross-linking to run a destriper.

**Comment by keskitalo** [comment]
This issue was addressed in 68b8e1e511a87c70f9d63798fb4f827c2796487d.
