### ISSUE TITLE
MPI locking around TIDAS writing does not work

### ISSUE THREAD

**Issue by tskisner** [hpc4cmb/toast#138]
The TIDAS library supports multiple MPI processes writing to a single **volume**, however each group within a block is (for the hdf5 backend) represented by a single file.  This means that only one process at a time can write to a single group.  In TOAST, a group represents the data for some number of detectors for one observation.  Since the data for one observation is distributed across processes, these processes must either take turns writing to the group, or the data must be gathered to a single writer.

The current implementation uses a locking mechanism (https://github.com/tskisner/mpi_shmem/blob/master/locking.py) to have every process take turns writing.  Although that locking works fine in a simple test (where every process gets the lock and then sleeps), using this in the actual TOAST code results in HDF5 errors that seem to indicate that the processes are stomping on each other and corrupting the file.

I have modified the HDF5 backend in tidas to be sure that it really is closing the file after each write, and also confirmed with the HDF5 developers that these commands should really close the file and flush all internal buffers.  I am hopeful this is a simple fix one we identify the source of the issue.

**Comment by tskisner** [comment]
I have been able to get writing to work in a branch on the small ground example (8 processes).  Rather than use a mutex lock, I simply serialize writing for processes working on a single observation.  I am backing out some debugging statements before opening a pull request.

**Comment by jrmadsen** [comment]
It is rather inefficient but I have resolved a similar problem with the serializer. Here is what it would look like (I think) in your case, assuming say, group #0 is rank 0-5, group #1 is 6-10, etc.:

``

**Comment by tskisner** [comment]
Fixed in upstream `pshmem` package.
