### ISSUE TITLE
Distributed Ring Map Data

### ISSUE THREAD

**Issue by tskisner** [hpc4cmb/toast#149]
We need a new class that stores distributed pixel values that are compatible with harmonic transforms.  This is one of the pieces needed by #148.  Each process will have a disjoint set of isolatitude rings.  The distribution of pixels will be compatible with libsharp.

The new class should be similar to the DistPixels class:
https://github.com/hpc4cmb/toast/blob/master/src/python/map/pixels.py#L117

and should take in the constructor the communicator, healpix nside, and number of nonzeros per pixel.  Does libsharp store (I,Q,U) values contiguously per pixel?  The constructor should use the same technique as this existing code:
https://github.com/hpc4cmb/toast/pull/145/files#diff-b09bed3487e621995f1f7d685f905064R34

The data member should be a toast.Cache() object:
https://github.com/hpc4cmb/toast/blob/master/src/python/map/pixels.py#L164

and should store the data values in one buffer and the pixel indices in another:
https://github.com/hpc4cmb/toast/blob/master/src/python/map/pixels.py#L182

The class should have some properties to access the communicator, nnz, etc.  It should also store the libsharp grid object.

**Comment by zonca** [comment]
implemented in #152, this issue can be closed
