### ISSUE TITLE
pipeline fails with no error if output folder is already created

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#151]
I am testing `toast` master on Edison.

If the output folder is already been created (as a symlink in my case but I don't think it matters)

I run a job with `toast_satellite_sim.py`, the job runs and no output `log` and no output maps are created in the output folder and no failure is logged in the stdout of the command saved by SLURM.

**Comment by keskitalo** [comment]
Could this rather be a case of extreme delay in the launch of the Python
job? I have certainly run the satellite script successfully with the output
folder already created. We have experienced very slow Python launches from
time to time on Edison.

**Comment by zonca** [comment]
I tested this with 4 30 min and 1 3:30h jobs, I don't think this is the problem. Maybe the symlink? I'll try with a normal folder and with a symlink and see if anything changes

**Comment by zonca** [comment]
I made other tests, I don't understand what was going on, I cannot reproduce it. I'll reopen if it happens again.
