### ISSUE TITLE
Debugging medium example possibly hanging on Edison

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#153]
Something on Edison changed, I cannot compile `toast` on Edison with the old `toast-deps`, a test recommended by @tskisner:

    module load toast-deps/20170707

See all modules:

```
module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.6                              14) dmapp/7.1.1-6.0.4.0_46.2__gb8abda2.ari
  2) nsg/1.2.0                                     15) gni-headers/5.0.11-6.0.4.0_7.2__g7136988.ari
  3) gcc/6.3.0                                     16) xpmem/2.2.2-6.0.4.0_3.1__g43b0535.ari
  4) craype-ivybridge                              17) job/2.2.2-6.0.4.0_8.2__g3c644b5.ari
  5) craype-network-aries                          18) dvs/2.7_2.2.31-6.0.4.1_6.1__gb3b87e6
  6) craype/2.5.12                                 19) alps/6.4.1-6.0.4.0_7.2__g86d0f3d.ari
  7) cray-mpich/7.6.0                              20) rca/2.2.15-6.0.4.1_13.1__g46acb0f.ari
  8) altd/2.0                                      21) atp/2.1.1
  9) darshan/3.1.4                                 22) PrgEnv-gnu/6.0.4
 10) cray-libsci/17.06.1                           23) intel/17.0.2.174
 11) udreg/2.3.2-6.0.4.0_12.2__g2f9c3ee.ari        24) cmake/3.8.1
 12) ugni/6.0.14-6.0.4.0_14.1__ge7db4a2.ari        25) toast-deps/20170707
 13) pmi/5.0.12
```

Is it expected that I have cray, intel and gnu all loaded simultaneously?

On today's `toast` master:

    ./autogen.sh
    module load fftw # it looks like it needs fftw or MKL
    ./platforms/edison-gcc.sh --prefix=$PREFIX

I get this link error:

```
libtool: link: CC -DNDEBUG -fopenmp -O3 -g -fPIC -o .libs/toast_test toast_test.o -fopenmp  ./.libs/libtoast.so /opt/cray/pe/fftw/3.3.4.6/sandybridge/lib/libfftw3f_mpi.so /opt/cray/pe/fftw/3.3.4.6/sandybridge/lib/libfftw3f_threads.so /opt/cray/pe/fftw/3.3.4.6/sandybridge/lib/libfftw3f.so /opt/cray/pe/fftw/3.3.4.6/sandybridge/lib/libfftw3_mpi.so -lmpich /opt/gcc/6.3.0/snos/lib/../lib64/libgfortran.so /opt/gcc/6.3.0/snos/lib/../lib64/libquadmath.so /opt/gcc/6.3.0/snos/lib/../lib64/libstdc++.so -lEl /opt/cray/pe/fftw/3.3.4.6/sandybridge/lib/libfftw3_threads.so /opt/cray/pe/fftw/3.3.4.6/sandybridge/lib/libfftw3.so -lm -pthread -fopenmp -Wl,-rpath -Wl,/opt/gcc/6.3.0/snos/lib/../lib64 -Wl,-rpath -Wl,/opt/cray/pe/fftw/3.3.4.6/sandybridge/lib
./.libs/libtoast.so: undefined reference to `__intel_sse4_strncmp'
```

@tskisner I am not sure it is worth debugging this issue just for a test, what do you think?

**Comment by zonca** [comment]
Instead with `toast-deps/20170809`:

```
module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.6                              14) dmapp/7.1.1-6.0.4.0_46.2__gb8abda2.ari
  2) nsg/1.2.0                                     15) gni-headers/5.0.11-6.0.4.0_7.2__g7136988.ari
  3) gcc/6.3.0                                     16) xpmem/2.2.2-6.0.4.0_3.1__g43b0535.ari
  4) craype-ivybridge                              17) job/2.2.2-6.0.4.0_8.2__g3c644b5.ari
  5) craype-network-aries                          18) dvs/2.7_2.2.31-6.0.4.1_6.1__gb3b87e6
  6) craype/2.5.12                                 19) alps/6.4.1-6.0.4.0_7.2__g86d0f3d.ari
  7) cray-mpich/7.6.0                              20) rca/2.2.15-6.0.4.1_13.1__g46acb0f.ari
  8) altd/2.0                                      21) atp/2.1.1
  9) darshan/3.1.4                                 22) PrgEnv-gnu/6.0.4
 10) cray-libsci/17.06.1                           23) intel/17.0.2.174
 11) udreg/2.3.2-6.0.4.0_12.2__g2f9c3ee.ari        24) git/2.9.1
 12) ugni/6.0.14-6.0.4.0_14.1__ge7db4a2.ari        25) cmake/3.8.1
 13) pmi/5.0.12                                    26) toast-deps/20170809
```
No need to load `fftw` here:

```
./autogen.sh
./platforms/edison-gcc.sh --prefix=$PREFIX
```

It builds successfully, now rerunning the medium test to check if it still hangs after 30min.

**Comment by zonca** [comment]
If I try to build with intel, with the latest `toast-deps`, there is a configuration problem, possibly due to the fact that `cc` is pointing to Cray's compiler:

```
./platforms/edison-intel.sh --prefix=$PREFIX
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking whether to compile using MPI... yes
checking for gcc... cc
checking whether the C compiler works... no
configure: error: in `/global/homes/z/zonca/p/software/toast':
configure: error: C compiler cannot create executables
See `config.log' for more details
edison[edison11] ~/p/software/toast master$ which cc
/opt/cray/pe/craype/2.5.12/bin/cc
```

**Comment by zonca** [comment]
@tskisner @keskitalo is there any useful test I can run? Once this is fixed I can continue running the sims on PICO.

**Comment by keskitalo** [comment]
Can you try running the medium satellite example again? I believe this was
a transient system issue.

-R

**Comment by keskitalo** [comment]
Hi Andrea,

The toast-deps module loads the intel programming environment and overloads
the compiler wrappers. You can check like this:

cc -v
icc version 18.0.0 (gcc version 6.3.0 compatibility)
...

I just configured and installed the toast master branch on Edison without
an issue. Here is my shell function for the environment on Edison:

  edideps () {
      export PS1="\e[0;35m[edideps]\e[m $(ppwd \l)\h:\W> "
      module unload altd
      module use /global/common/software/cmb/edison/modulefiles
      module load toast-deps/20171126
      export
TOASTROOT=/global/common/software/cmb/edison/toast-deps/20171126_conda
      export
AUXROOT=/global/common/software/cmb/edison/toast-deps/20171126_aux
      export PREFIX=/scratch3/scratchdirs/keskital/software-toastdeps
      unset PYTHONSTARTUP
      export CRAYPE_LINK_TYPE=dynamic
      export PYTHONPATH=$PREFIX/lib/python3.6/site-packages:$PYTHONPATH
      export CC=icc
      export CXX=icpc
      export F77=ifort
      export FC=ifort
      export MPICC=cc
      export MPICXX=CC
      export OPENMP_CFLAGS="-qopenmp"
      export OPENMP_CXXFLAGS="-qopenmp"
      export CFLAGS="-O3 -g -fPIC -xavx -pthread"
      export CXXFLAGS="-O3 -g -fPIC -xavx -pthread"
      export FCFLAGS="-O3 -g -fPIC -xavx -pthread -heap-arrays 16"
      export CPPFLAGS="-I$PREFIX/include -I$PREFIX/include
-I${TOASTROOT}/include -I${AUXROOT}/include"
      export LDFLAGS="-qopenmp -L$PREFIX/lib -L${TOASTROOT}/lib
-L${AUXROOT}/lib"
      export PATH=$PREFIX/bin:$PATH
      export LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH
      export LD_LIBRARY_PATH=$PREFIX/lib64:$LD_LIBRARY_PATH
      export LDSHARED="icc -shared"
  }

Not all of this is relevant for you but you might want to give it a go just
as it is.

-R

**Comment by zonca** [comment]
I'm using a much older `toast-deps`! 
Docs say to use

    module use /global/common/${NERSC_HOST}/contrib/hpcosmo/modulefiles
 
see http://hpc4cmb.github.io/toast/nersc.html, but you are using 

     module use /global/common/software/cmb/edison/modulefiles

**Comment by zonca** [comment]
I'll switch to the newer module and run the test again

**Comment by zonca** [comment]
Even using the newer module I had the same exact issue.

Instead, using the `toast` version compiled by @keskitalo , the medium example ran in 2 minutes.

Can we re-create Reijo's environment in a `toast` module so that people wanting to just use toast on Edison can use that?
Or/And, can Reijo or Ted write documentation on how to compile `toast` the way Reijo did it?

I'll try to run the PICO example with Reijo's toast in the next days

**Comment by tskisner** [comment]
This is strange- I have compiled toast against both the latest and the previous toast-deps versions multiple times today.  The documentation is not up to date...

**Comment by tskisner** [comment]
@zonca , I see you are using the gcc config on edison- the toast-deps install is only compatible with the Intel compilers.

**Comment by tskisner** [comment]
@keskitalo and I are iterating on this offline.

**Comment by tskisner** [comment]
@zonca , we tracked this down to the Cray "altd" module.  Simply unloading that module lets the jobs start.  I have modified the installed toast-deps module file to explicitly unload altd.  So you should now be able to do:
```
module use /global/common/software/cmb/{edison|cori|coriknl}/modulefiles
module load toast-deps
cd toast
./autogen.sh
./platforms/edison-intel.sh --prefix=<blah>
```
(or similarly with the platform scripts for cori-haswell and cori-knl).  I'll open a pull request in a second that also updates the satellite example pipeline to flush stdout and catch exceptions and do MPI_Abort().
