### ISSUE TITLE
Implement or find PCG solver

### ISSUE THREAD

**Issue by tskisner** [hpc4cmb/toast#18]
Scipy has generic solvers, so perhaps we can use them.  The critical feature is that we need to be able to  perform MPI communication inside the left hand side evaluation.  This solver is needed for both the full GLS mapmaking ported from TOAST, and also for the destriper.  This issue is to track search results on this topic.

**Comment by msyriac** [comment]
Check out Sigurd Naess' (@amaurea) implementation here:
https://github.com/amaurea/enlib/blob/master/cg.py

It is MPI-friendly in that you can specify explicitly how the dot product is done.

**Comment by tskisner** [comment]
I think we can close this.  There are many examples of solvers in python and in our own code from the last 15 years.  This is something @keskitalo can revisit as part of #258.
