### ISSUE TITLE
Please read this important note about memory results in “timing_output_XXX.out”

### ISSUE THREAD

**Issue by jrmadsen** [hpc4cmb/toast#183]
This will greatly clarify how these reports will help us fix our memory issues in large scale runs. 

This is in the docs but is worth repeating here. 

### These timing (+memory) reports allow one to **DEDUCE THE TEMPORARY MEMORY USAGE**. ###

Note: RSS stands for "resident set size". It is the amount of memory that currently resides in RAM (i.e. excludes swap)

- A total of 4 numbers of reported alongside the timing results
  - There are two groups of values reported
    - The first group is the “total RSS”
      - This is the RSS measurements at the end of the function
      - Recorded during the destructor of the auto-timer
    - The second group is the “self RSS”
      - This is the total RSS subtracted from the RSS measurement at the beginning of the function
      - This group will display memory from this function 
      - Recorded during the construction of the auto-timer
  -  Each group has two values: "peak" and "curr" (current)
      - "peak" RSS is what the OS reports as the maximum memory usage of the process
        - If the OS has swap, this may at times dip down but if there is no swap, it should not
      - "curr" RSS is the current size of the memory calculated from (# of memory pages) * (size of memory page)
      
### For example, if a function reports a self RSS "peak" of 900 MB and the self RSS "curr" is 300 MB, this means that the function either allocated or is returning an object requiring 300 MB of memory but used an additional 600 MB of temporary memory that was freed/released during the function. ###

Please reference the _**Timing Results**_ section of the docs for further information and examples.

**Comment by zonca** [comment]
thanks @jrmadsen where can I find the timing results of the mega run?

**Comment by jdborrill** [comment]
There were none, since none of the runs completed.

**Comment by zonca** [comment]
I am interesting to see a run of PySM / libsharp with memory information and timing. @keskitalo do you think we can run an example representative of a real simulation? If you send me some suggestions I can take care of running it. In principle it would be nice to do this in the context of the PICO sims if #159 is fixed.

**Comment by zonca** [comment]
@jrmadsen where do I find docs on how to configure timing?

**Comment by zonca** [comment]
@jrmadsen nevermind, found it at the bottom of https://github.com/hpc4cmb/toast/blob/master/doc/timing.rst

**Comment by zonca** [comment]
@jrmadsen I just ran `tiny-satellite` example on Edison,

I get this in the timing:

    |0> [pyc] |_rotate                              :  0.028 wall,  0.010 user +  0.000 system =  0.010 CPU [sec] ( 35.3%) :    RSS {tot,self}_{curr,peak} : (   0.0|   0.0) | (105608380.4|  98.4) [MB] (total # of laps: 4)

is it possible there is a unit conversion issue in the current memory?
I am currently testing this branch: https://github.com/hpc4cmb/toast/pull/194

**Comment by jrmadsen** [comment]
Yes, Linux likes to report in KB and macOS in MB and a recent update has a unit error I caught recently when re-packaging. I will commit the fixes. This has proved useful so I have repackaged this whole sub-suite into a stand-alone GitHub repo so that it can be used in other C++ and Python applications:

https://github.com/jrmadsen/TiMemory.git

It has an MIT license (very permissive) and includes an over-ride to change the outer-namespace (e.g. -DTIMEMORY_NAMESPACE=toast) so it would be possible to just keep a copy of this repo and add it as a subproject in CMake like with Cereal. It has a bunch of extensions too that support recursive functions, better thread-safety, and direct access to the routines for plotting. 

Another post-doc wants to use it so the plan is to get it into pip sometime soon.

Jonathan

—

Jonathan R. Madsen
Lawrence Berkeley National Laboratory
email: jrmadsen@lbl.gov
work: +1 (510) 486-7658

**Comment by jrmadsen** [comment]
This issue has been fixed in the master branch.

—

Jonathan R. Madsen
Lawrence Berkeley National Laboratory
email: jrmadsen@lbl.gov
work: +1 (510) 486-7658

**Comment by zonca** [comment]
ok, thanks, it works as expected now, I think we can close this issue
