### ISSUE TITLE
Replace args in pipeline script functions

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#202]
in the ground sim pipeline script, most functions get the `args` variable as input, this is convenient but it makes it difficult to understand what actually is needed by that function.

I can replace `args` with all the actual args properties. e.g.

    def simulate_sky_signal(args, comm, data, counter, schedules, subnpix, localsm): 
        pysm_model=args.input_pysm_model
        nside=args.nside

to:

    def simulate_sky_signal(pysm_model, nside, comm, data, counter, schedules, subnpix, localsm):                                                    

@tskisner @keskitalo would this be useful? or are you already refactoring some other way?

**Comment by keskitalo** [comment]
There is a reason why PyLint enforces a low limit on the number of arguments to functions. Long lists of positional parameters make it easy to confuse the arguments, especially with loosely typed languages like Python.

Picking the relevant parameters from `args` only works to a certain extent. @tskisner has floated around the idea of breaking down the parameters by operator. Is it time to pursue that more aggressively?

**Comment by zonca** [comment]
I would also consider never use positional arguments.

Il gio 25 gen 2018, 18:31 Reijo Keskitalo <notifications@github.com> ha
scritto:

**Comment by tskisner** [comment]
We had previously talked about each operator constructor taking a dictionary of config parameters that could be read from a JSON / YAML file.  So for complicated pipelines you could just pass in one (or multiple) config files that specified the parameters for the different operators.

For example, if I wanted to have a pipeline that did a bunch of "standard" simulations and then applied my own custom processing, then I could pass a standard config file that had the options for those simulation operators and then just customize a different config file for my new processing operator.

Obviously it is trivial to take a dictionary and convert to **kwargs, whatever is easier to parse in the constructor.

**Comment by zonca** [comment]
@tskisner I think this would be a good solution.

A pipeline gets a JSON file as input, it reads and broadcasts it. Inside this JSON there is one nested dictionary for each Operator, like:

```
{ 
    "OpSimPySM" : {
        "pysm_model" : "s3,d7,f1,a2,c2",
        "apply_beam" : false,
                               }
}
```

then in the pipeline we call the operator and pass this config dictionary:

```
tt.OpSimPySM(       comm=comm.comm_rank,
                                out=signalname,
                                config=config["OpSimPySM"]
)
```

@tskisner do you want me to work on a first draft of this so we can see how it looks like?

**Comment by tskisner** [comment]
That is fine with me, @keskitalo any thoughts / preferences on a design like this?

**Comment by keskitalo** [comment]
Can we make it so that one can supply multiple JSON files and they are either concatenated by the pipeline or the pipeline will search through all of them when looking for the configuration for a specific pipeline module?

**Comment by tskisner** [comment]
I think that is a good idea- we should have a helper function that all pipelines can use to read in a list of json files and update() a single dict with those results.  This way you can have a "canonical" parameter file for things like atmosphere sims, etc.  And we can put those files in version control.

**Comment by zonca** [comment]
I am thinking about this, this post convinced me to avoid JSON (worst thing is not supporting comments) https://arp242.net/weblog/json_as_configuration_files-_please_dont, what about just using `.ini` files?

`ConfigParser` already supports multiple configuration files and the section `[DEFAULT]` can be used to give a set of defaults, but even better, if you read a list of `ini` files, the first can have default values that are optionally overwritten by the following.

Do you think this is ok?

**Comment by keskitalo** [comment]
Seems flexible enough to me. @tskisner ?

**Comment by tskisner** [comment]
I agree that comments are a great feature.  I am most familiar with config files done in YAML, which allow also storing type information (int/float/double) when serialized from python.  However, that is probably not so important for this case.  I had not considered the feature of keeping default values while updating selected ones.  Obviously yaml could do this too with a "default" sub-dictionary and a "user" or "options" sub-dictionary.

Looking at the configparser docs, there are helper methods for ```getint()```, ```getfloat()```, etc so we can at least check the type conversion when parsing the values.  If you are willing to work on this and like ```ini``` files, then I'm happy to try it :-)

**Comment by zonca** [comment]
of course, I'll try to implement a mixed solution first where just a couple of operators use configfiles and the rest still the arguments, so I can get some early feedback.

**Comment by tskisner** [comment]
This issue is related to #157 and #260.  Basically there will be a toast.pipeline submodule of high-level functions, and one of those should be "instantiate an operator with a dictionary (which could be read from a file)".  This would work as long as all operators took only kwargs and no positional args in their constructors (so that one could pass in a dictionary).

**Comment by tskisner** [comment]
Just a note that @keskitalo has taken the first step towards this work in #280, by moving the operator setup into a toast.pipeline package.

**Comment by tskisner** [comment]
Closing this in favor of the updated issue #340.
