### ISSUE TITLE
Units in pipelines arguments

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#207]
What about having units inside names of the arguments of the pipelines?
Like:

* `input_dipole_solar_speed_kms`
* `input_dipole_solar_gal_lat_deg`

It is more verbose but `.par` files would be self-explanatory

**Comment by keskitalo** [comment]
I like it. Presently the units are documented in the help strings but those are not always easily accessible.

**Comment by zonca** [comment]
ok good, I used this for dipole and I plan on modifying other pipelines arguments when I happen to modify a pipeline
