### ISSUE TITLE
Running CMake requires access to NERSC

### ISSUE THREAD

**Issue by keskitalo** [hpc4cmb/toast#214]
CMake will fetch the example data by default and hangs if NERSC is unreachable.

**Comment by jrmadsen** [comment]
- Added an option to disable generating the examples: `-DGENERATE_EXAMPLES={ON,OFF}`
- Added a timeout to cleanup (30 s), fetch_data (60 s), and generate_shell (30 s) scripts so cron jobs won't hang forever
