### ISSUE TITLE
Implement more dict-like behavior for toast.Data

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#215]
What about making `toast.Data` more dictionary-like supporting key access and membership testing?

key access:
`tod.cache.reference["signal_ch_1A"]` -> `tod.cache["signal_ch_1A"]`

membership testing:
`if tod.cache.exists("signal_ch_1A"):` -> `if "signal_ch_1A" in tod.cache:`

If you agree I can implement it.

current code is in https://github.com/hpc4cmb/toast/blob/master/src/python/cache.py#L293

**Comment by tskisner** [comment]
I think that sounds like a cool idea, but we should be careful of merge conflicts with @jrmadsen's work in PR #191.  @keskitalo , what do you think?

**Comment by zonca** [comment]
I can implement it after #191 is merged

Il gio 8 feb 2018, 16:26 Theodore Kisner <notifications@github.com> ha
scritto:

**Comment by keskitalo** [comment]
I think we'll want the user explicitly to state whether they want a reference or a copy of the cache object. That allows the cache to use the BurstBuffer or other disk backend. If the user makes a copy of a reference themself, then `Cache` is left thinking that the object is being modified in place. 

The membership testing part looks nice.

**Comment by zonca** [comment]
How do you make a copy?

**Comment by keskitalo** [comment]
Jonathan is adding a `copy()` method in the PR.

**Comment by tskisner** [comment]
Revisiting this old issue.  Every observation is independent in terms of detectors, sampling, etc.  So it is not possible to represent the full dataset as a single dictionary-like thing.  However, we **can** do a better job on the interfaces to data in a single observation.  See #334.  Closing this issue in favor of discussion on that proposal.
