### ISSUE TITLE
Madam destriping issue on PySM sims

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#222]
I am experiencing an issue in the pico simulations.

The madam destriped maps don't have any signal, while the binned maps looks fine. For now I am running a test simulation with only PySM input sky and a tiny amount of noise.

@keskitalo can you please take a quick look to my configuration files and see if anything looks wrong? https://github.com/zonca/pico-simulations/pull/4/files

If they look fine, do you have suggestions on how to debug this?

![destriped](https://user-images.githubusercontent.com/383090/36700944-adc78a0e-1b51-11e8-9c0e-b703ecb15be4.png)
![binned](https://user-images.githubusercontent.com/383090/36700945-ade9f56c-1b51-11e8-9553-ccb255f74e05.png)

**Comment by keskitalo** [comment]
@zonca That is unexpected... Do you bin the map with Madam as well? Can I see your logs?

**Comment by zonca** [comment]
yes, with Madam, see `/global/cscratch1/sd/zonca/pico/cal_sims/60days_noiseless_skyonly`

**Comment by keskitalo** [comment]
I see you are using the `allreduce` communication pattern.  Are you running against a version of `libmadam` that includes this bugfix: https://github.com/hpc4cmb/libmadam/commit/770f84d9e105caa738da0e715efc29a959f663af ?

**Comment by zonca** [comment]
thanks @keskitalo ! that was the issue
