### ISSUE TITLE
Pointing jump across observation

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#224]
In PICO simulations for calibration work with @ziotom78 I have hit a issue in pointing.

As we already discussed I have a version of `toast_satellite_sim.py` that dumps timelines to FITS (https://github.com/zonca/toast/pull/1/files).

I noticed that across observations there is a significant jump in pointing, see the following plot of 200 minutes of THETA across the observation boundary.

![theta](https://user-images.githubusercontent.com/383090/36948831-d7af4558-1fe0-11e8-80a6-445edf3877ad.png)

How do you suggest to debug this?

**Comment by zonca** [comment]
would it be helpful if I try to reproduce this in the tiny satellite example?

**Comment by tskisner** [comment]
For this run, how long are the simulated gaps between science observations?  Zero?

**Comment by zonca** [comment]
Yes zero


Il mar 6 mar 2018, 16:35 Theodore Kisner <notifications@github.com> ha
scritto:

**Comment by zonca** [comment]
@tskisner I think this happens also in the tiny satellite example.
I have reduced the `gap` from 4 hours to 0 and dumped the first and last quaternion for each of the 32 observations of the first channel:

https://gist.github.com/zonca/5d0b577e29301fcdeb47c3286a177aec

**Comment by tskisner** [comment]
Ok, is this just the phase of the scan being reset each observation? (I
will check soon).  If that is happening I would not have noticed, since I
usually have a gap in time between observations.
