### ISSUE TITLE
Failure on Cori with runtime_error with conviqt

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#253]
I ran a small test simulation with conviqt 2 weeks ago and it was working fine.
Now I am resubmitting the same job with the same version of toast (the branch in #241) and I get a failure.

The main issue is that the error message is very generic.

```
terminate called after throwing an instance of 'std::runtime_error'                                                                 
```

The full log is at `/global/cscratch1/sd/zonca/pico/conviqt_sim/201806_boresight_1pix_conviqt_realbeams_10h/log`

my config files at `/global/cscratch1/sd/zonca/pico-simulations/conviqt_sim`

I am using `toast-deps/20180606`

Do you have suggestions on how to debug this? or what might have changed in the last 2 weeks on Cori or toast-deps (I also recompiled TOAST before running this simulation).

**Comment by keskitalo** [comment]
That exception is being thrown from compiled code so probably `libconviqt`. If it does not go away by recompiling libconviqt, you should run it in the verbose mode to see where the problem is coming from.

**Comment by tskisner** [comment]
Once #251 is merged, we'll be able to support conviqt unit tests :-)  Cori was just upgraded to a newer version of userspace tools (CDT = Cray Development Toolkit).  So the default module versions have changed.  I don't think that should impact us, but I'll install a new toast-deps version once I get the travis tests working for #251 (almost there).

**Comment by zonca** [comment]
@tskisner Please let me know when you compile convict again, I'll Try To Run it

**Comment by zonca** [comment]
@tskisner I finally tried to rerun my `conviqt` example again using the new `toast-deps/20180716` module.

I am still getting the same `runtime_error`, full log in:

    /global/cscratch1/sd/zonca/pico/conviqt_sim/201806_boresight_1pix_conviqt_realbeams_10h

I am not compiling `libconviqt` myself but relying on `toast-deps`.

The files for my small test run are in https://github.com/zonca/pico-simulations/tree/conviqt/conviqt_sim
would you like to try run them directly and check if you get the same failure?

**Comment by zonca** [comment]
this is fixed recompiling everything
