### ISSUE TITLE
update the published toast documentation

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#255]
the documentation at http://hpc4cmb.github.io/toast/ is quite old, would it be possible to update it?
For example it still has `%> python -c "import toast; toast.test()"` for running tests.

**Comment by tskisner** [comment]
The documentation updates are the next task.  I did not want to hold up the 2.3 release for this, but readthedocs configuration is working to install the package prior to the sphinx build.

**Comment by tskisner** [comment]
Documentation is now up to date on readthedocs.  Closing this, but we should open specific issues for any problems / improvements that remain.

**Comment by zonca** [comment]
@tskisner please disable the old docs at http://hpc4cmb.github.io/toast/

Also, I recently figured out a way out of readthedocs: https://zonca.dev/2020/09/migrate-travisci-readthedocs-github-actions.html
