### ISSUE TITLE
Migrate CI to travis-ci.com

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast#344]
I am migrating healpy from travis-ci.org to travis-ci.com, still free for open source but more features.

https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

I think a helpful feature is that it allows cron builds. So you can check master every month to check nothing broke due to dependency changing.

You need to click the "join to beta" in the settings for the `hpc4cmb` organization and then migrate the repos.

If not interested just close the issue.

**Comment by tskisner** [comment]
Ok, thanks for the heads up.  I'm working on some travis deployment items in a branch now- let's do this after that is merged.  Will leave this issue open so we don't forget about it.

**Comment by tskisner** [comment]
Just a note that I recently moved a project to use github actions / workflows:

https://github.com/hpc4cmb/cmbenv/blob/master/.github/workflows/test.yml
https://github.com/hpc4cmb/cmbenv/blob/master/.github/workflows/deploy.yml

And was very happy with the result.  They allow long-running (6 hour) jobs and support all the usual things (workflows are configured on specific git repo actions like push, PR, tag, etc and there are multistage jobs).  The repo above is where I am now building docker containers with toast dependencies that we can use in the toast CI tests.

I'll open a demonstration PR for more feedback, but would be curious if you have experienced any problems with github actions vs travis.

**Comment by zonca** [comment]
I have no experience with GitHub actions , but they look very promising!
