### ISSUE TITLE
TypeError: Center-and-width format in toast_ground_schedule.py

### ISSUE THREAD

**Issue by Ankurdev-astro** [hpc4cmb/toast#459]
Using Center-and-width format in toast_ground_schedule.py throws :
```
"Highest possible observing elevation: {:.2f} degrees."
TypeError: unsupported format string passed to NoneType.__format__
```

**Note:** Works and No error when --debug option in  toast_ground_schedule.py is used. Also works Rectangular format. 

![TOAST_TypeError](https://user-images.githubusercontent.com/34693706/133449428-98c5227e-3234-47fb-afb2-4bfcff89ada7.png)

**Comment by keskitalo** [comment]
Thank you for raising the issue! I just tried running your command line against the head of the `master` branch. It didn't reproduce the problem so it may be an issue that was already fixed. Are you in the position to update TOAST or are you using a system-wide install at NERSC (for example)?

**Comment by Ankurdev-astro** [comment]
Thank you for your reply. Yes, you are correct, the issue has been solved after building from the master branch. Thanks
[SOLVED]
