### ISSUE TITLE
Parallel unit tests hang when failure does not occur on root process

### ISSUE THREAD

**Issue by keskitalo** [hpc4cmb/toast#495]
I recently had a bunch of CI tests time out because of a broadcasting error on process # 3. The only thing printed to the log is `[3] error` and the job hangs. I had to add a `try...catch` around the failing test to get a stack trace. Seems like we should make something similar the default for parallel unit tests.

**Comment by tskisner** [comment]
This should be fixed (again) in #615 .  There is now a unit test that runs a script where one process raises and verifies the shell exit code is non-zero.
