### ISSUE TITLE
Atacama weather measurements?

### ISSUE THREAD

**Issue by suinnelee** [hpc4cmb/toast#525]
Would there be any way to find out where the data for the weather_Atacama.fits file were measured? The TS value seems to deviate a bit from the expected surface temperature found online, and I supposed this was because of the elevation. It would be best to clarify this before I moved onto swapping the weather data on my relevant site.

**Comment by keskitalo** [comment]
Merra-2 data were retrieved for the one cell that contained the observatory
coordinates. I believe I used the POLAR BEAR location.

**Comment by suinnelee** [comment]
I see, thanks a lot!
