### ISSUE TITLE
madam.py small logic error

### ISSUE THREAD

**Issue by bcrill** [hpc4cmb/toast#61]
Hi guys:

https://github.com/hpc4cmb/toast/blob/master/toast/map/madam.py#L318

if self._apply_flag is False and self._purge is True, then the variable cacheflagname is accessed prior to initialization.

Should be easy to fix!

Cheers,

Brendan

**Comment by keskitalo** [comment]
Thanks Brendan!

-R

**Comment by keskitalo** [comment]
Fixed in bff65f77ff5105c7cc2796a6ebd803e97b8e338c
