### ISSUE TITLE
Missing import in schedule.py

### ISSUE THREAD

**Issue by mhasself** [hpc4cmb/toast#623]
On version '3.0.0a9', schedule.py imports dateutil but not dateutil.parser.

```
import toast.schedule
schedule = toast.schedule.GroundSchedule()
schedule.read('jupiter.txt')
```
fails with `AttributeError: module 'dateutil' has no attribute 'parser'`

But this works great:
```
import dateutil.parser
import toast.schedule
schedule = toast.schedule.GroundSchedule()
schedule.read('jupiter.txt')
```

**Comment by tskisner** [comment]
Hi @mhasself , just confirming that this is using the wheel of 3.0.0a9?  I don't see a problem locally with toast installed with conda compilers:
```
$ python
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import toast.schedule
>>> 
```
And[ I see that import](https://github.com/hpc4cmb/toast/blob/ddae67de4154067d2317999f6cf6c31dd48ae047/src/toast/schedule.py#L14) in `schedule.py`.  I will test if there is problem with the wheel.

**Comment by tskisner** [comment]
Got it- yes it looks like somehow that import got removed between master and toast3 branches.  I'm not sure why we haven't seen that problem until now, but I'll fix it.

**Comment by tskisner** [comment]
Hopefully fixed in trivial PR #624.

**Comment by tskisner** [comment]
I'll leave this open until the next tag and wheel confirms the fix.

**Comment by mhasself** [comment]
Thanks!

**Comment by keskitalo** [comment]
Closing a resolved issue.
