### ISSUE TITLE
Noise model PSD spacing

### ISSUE THREAD

**Issue by tskisner** [hpc4cmb/toast#64]
The current noise PSD model is not being generated at high enough resolution for the interpolation.  Also, we probably remove the built-in high pass in this model.

**Comment by tskisner** [comment]
Some more investigations into this.  First, to review:

1.  toast uses the historical f_knee / f_min analytic noise model that prevents the spectrum from blowing up when sampled at very low frequency.

2.  toast does dynamic binning in frequency when generating the PSD.  The first bin is set at f_min, and then the bins are doubled in size until a frequency of 10*f_knee.  At that point the noise should be be very white, and then 10 uniform bins are used from that point up until Nyquist.

Here is the problem:  The toast PSD object assumes a constant frequency binning for all PSDs.  In order to set the bin size it chooses one of the f_knee values.  If the PSDs are vastly different, or representing different things (think common mode noise), then this has bad unintended consequences.

The solution is to have every PSD associated with its own vector of frequencies.  This requires changing the Noise base class and the AnalyticNoise class in a trivial way.

**Comment by jdborrill** [comment]
I'm confused, since the problem showed up in single-detector runs with the
same PSD throughout, so all the PSDs *should* have had the same binning.

Julian

**Comment by tskisner** [comment]
The case which I can see more easily is in the unit test when there are several detectors, including one with white noise (f_knee=0).  This f_knee value was being used to set the frequency binning, cause all detectors to have equal spaced (and very large) frequency bins.  There may be several issues going on.  I'll fix this first one and then try to reproduce the issue with f_knee very low (1mHz).

**Comment by tskisner** [comment]
I just opened a pull request which fixes this and potentially other issues.  Attached are the output plots generated by the unit tests showing the improved spacing of the simulated PSDs.
![simnoise](https://cloud.githubusercontent.com/assets/84221/19246518/97de5d02-8edb-11e6-8c51-fc581d197753.png)

**Comment by tskisner** [comment]
Note that the one "bad" looking case is designed to be bad- it has a knee frequency of 2Hz (for a sample rate of 20Hz), so there is essentially no white noise plateau.

**Comment by tskisner** [comment]
Fixed by a1834393441c65cc783d60cb08c74f9226a6d66e.
