### ISSUE TITLE
Cannot override tuple-valued traits from command line

### ISSUE THREAD

**Issue by keskitalo** [hpc4cmb/toast#707]
It does not seem that there is any way to override operator traits that expect a tuple from the command line.

Example: `toast.ops.pixels_wcs.PixelsWCS.resolution`

**Comment by tskisner** [comment]
All container traits can be specified with their string representation, which is fed through `ast.literal_eval()` [to get the value](https://github.com/hpc4cmb/toast/blob/ad6589f333736c94ea2eca81f6d1477a327458fb/src/toast/config.py#L906).  [Example from the unit tests](https://github.com/hpc4cmb/toast/blob/ad6589f333736c94ea2eca81f6d1477a327458fb/src/toast/tests/config.py#L429).  I use this routinely with `PixelsWCS` resolution.

**Comment by keskitalo** [comment]
Beautiful!
