### ISSUE TITLE
Elemental Library is required for building from source; not optional

### ISSUE THREAD

**Issue by triskadecaepyon** [hpc4cmb/toast#87]
When building TOAST from source, Elemental is a strict requirement and not optional, as the documentation alludes to.  

In toast/src/libtoast/toast.cpp with HAVE_ELEMENTAL, the IFDEF will break the namespace of toast when compiling the c++ dependencies.  

Configure, make, and the documentation should be modified to reflect this.

**Comment by tskisner** [comment]
This should be fixed in d56daced3da464674e4a071e661c901054f54f25.  I forgot to add ifdef checks in the C language bindings.
